edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
merge_imports = true
reorder_imports = true
reorder_modules = true
comment_width = 100
wrap_comments = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
