language = "C"
include_guard = "AETHER_H"
tab_width = 4
style = "both"
cpp_compat = true

[defines]
"target_os = windows" = "AETHER_WINDOWS"

[export]
include = ["aether_.*"]

[export.rename]
"AetherProvider" = "AetherProvider"
"AetherEngine" = "AetherEngine"
"AetherTemplate" = "AetherTemplate"

[fn]
rename_args = "SnakeCase"

[struct]
rename_fields = "SnakeCase"

[enum]
rename_variants = "ScreamingSnakeCase"
